import type { Payload, RequiredDataFromCollectionSlug } from 'payload'

const skills: RequiredDataFromCollectionSlug<'skills'>[] = [
  // Core stack (showOnStack: true) - displayed in Tech Stack section
  {
    name: 'Next.js',
    description: 'React Framework',
    category: 'frontend',
    url: 'https://nextjs.org',
    order: 100,
    showOnStack: true,
  },
  {
    name: 'React',
    description: 'Frontend Library',
    category: 'frontend',
    url: 'https://react.dev',
    order: 98,
    showOnStack: true,
  },
  {
    name: 'TypeScript',
    description: 'Type-safe JavaScript',
    category: 'frontend',
    url: 'https://www.typescriptlang.org',
    order: 96,
    showOnStack: true,
  },
  {
    name: 'Tailwind CSS',
    description: 'Utility-first CSS',
    category: 'frontend',
    url: 'https://tailwindcss.com',
    order: 94,
    showOnStack: true,
  },
  {
    name: 'React Native',
    description: 'Mobile Framework',
    category: 'frontend',
    url: 'https://reactnative.dev',
    order: 92,
    showOnStack: true,
  },
  {
    name: 'Expo',
    description: 'React Native Toolchain',
    category: 'frontend',
    url: 'https://expo.dev',
    order: 90,
    showOnStack: true,
  },
  {
    name: 'TanStack Query',
    description: 'Server-state & Data Fetching',
    category: 'frontend',
    url: 'https://tanstack.com/query',
    order: 88,
    showOnStack: true,
  },
  {
    name: 'TanStack Table',
    description: 'Headless Tables & Data Grids',
    category: 'frontend',
    url: 'https://tanstack.com/table/v8',
    order: 86,
    showOnStack: true,
  },
  {
    name: 'Payload CMS',
    description: 'Headless CMS',
    category: 'backend',
    url: 'https://payloadcms.com',
    order: 84,
    showOnStack: true,
  },
  {
    name: 'MongoDB',
    description: 'NoSQL Database',
    category: 'backend',
    url: 'https://www.mongodb.com',
    order: 82,
    showOnStack: true,
  },

  // Additional skills (showOnStack: false) - used in experience/project tags
  {
    name: 'tRPC',
    description: 'Type-safe APIs',
    category: 'backend',
    url: 'https://trpc.io',
    order: 80,
    showOnStack: false,
  },
  {
    name: 'Vercel',
    description: 'Deployment Platform',
    category: 'tools',
    url: 'https://vercel.com',
    order: 78,
    showOnStack: false,
  },
  {
    name: 'Cloudflare R2',
    description: 'Object Storage',
    category: 'backend',
    url: 'https://www.cloudflare.com/products/r2/',
    order: 76,
    showOnStack: false,
  },
  {
    name: 'AWS S3',
    description: 'Object Storage',
    category: 'backend',
    url: 'https://aws.amazon.com/s3/',
    order: 74,
    showOnStack: false,
  },
  {
    name: 'OneSignal',
    description: 'Push Notifications',
    category: 'backend',
    url: 'https://onesignal.com',
    order: 72,
    showOnStack: false,
  },
  {
    name: 'MSG91',
    description: 'OTP & SMS APIs',
    category: 'backend',
    url: 'https://msg91.com/developers',
    order: 70,
    showOnStack: false,
  },
  {
    name: 'Express.js',
    description: 'Web Framework',
    category: 'backend',
    url: 'https://expressjs.com',
    order: 68,
    showOnStack: false,
  },
  {
    name: 'Node.js',
    description: 'JavaScript Runtime',
    category: 'backend',
    url: 'https://nodejs.org',
    order: 66,
    showOnStack: false,
  },
  {
    name: 'Git',
    description: 'Version Control',
    category: 'tools',
    url: 'https://git-scm.com',
    order: 64,
    showOnStack: false,
  },
  {
    name: 'GitHub',
    description: 'Code Hosting',
    category: 'tools',
    url: 'https://github.com',
    order: 62,
    showOnStack: false,
  },
  {
    name: 'nuqs',
    description: 'URL State Management',
    category: 'frontend',
    url: 'https://nuqs.47ng.com',
    order: 60,
    showOnStack: false,
  },
  {
    name: 'shadcn/ui',
    description: 'Component Collection',
    category: 'frontend',
    url: 'https://ui.shadcn.com',
    order: 58,
    showOnStack: false,
  },
  {
    name: 'Shadcn/UI',
    description: 'Component Collection',
    category: 'frontend',
    url: 'https://ui.shadcn.com',
    order: 56,
    showOnStack: false,
  },
  {
    name: 'Framer Motion',
    description: 'Animation Library',
    category: 'frontend',
    url: 'https://www.framer.com/motion/',
    order: 54,
    showOnStack: false,
  },
  {
    name: 'Astro',
    description: 'Static Site Generator',
    category: 'frontend',
    url: 'https://astro.build',
    order: 52,
    showOnStack: false,
  },
  {
    name: 'WP to Payload Migration',
    description: 'CMS Migration',
    category: 'tools',
    url: 'https://payloadcms.com',
    order: 50,
    showOnStack: false,
  },
  {
    name: 'Electron',
    description: 'Desktop Apps',
    category: 'frontend',
    url: 'https://www.electronjs.org',
    order: 48,
    showOnStack: false,
  },
  {
    name: 'RabbitMQ',
    description: 'Message Queue',
    category: 'backend',
    url: 'https://www.rabbitmq.com',
    order: 46,
    showOnStack: false,
  },
  {
    name: 'Chart.js',
    description: 'Charting Library',
    category: 'frontend',
    url: 'https://www.chartjs.org',
    order: 44,
    showOnStack: false,
  },
  {
    name: 'Recharts',
    description: 'React Charts',
    category: 'frontend',
    url: 'https://recharts.org',
    order: 42,
    showOnStack: false,
  },
  {
    name: 'Radix UI',
    description: 'Accessible Components',
    category: 'frontend',
    url: 'https://www.radix-ui.com',
    order: 40,
    showOnStack: false,
  },
  {
    name: 'Zustand',
    description: 'State Management',
    category: 'frontend',
    url: 'https://zustand-demo.pmnd.rs',
    order: 38,
    showOnStack: false,
  },
  {
    name: 'React Hook Form',
    description: 'Form Library',
    category: 'frontend',
    url: 'https://react-hook-form.com',
    order: 36,
    showOnStack: false,
  },
  // Soft skills for non-tech experiences
  {
    name: 'Team Leadership',
    description: 'Leadership Skills',
    category: 'other',
    order: 20,
    showOnStack: false,
  },
  {
    name: 'Communication',
    description: 'Soft Skills',
    category: 'other',
    order: 18,
    showOnStack: false,
  },
  {
    name: 'Negotiation',
    description: 'Business Skills',
    category: 'other',
    order: 16,
    showOnStack: false,
  },
  {
    name: 'Operations',
    description: 'Management Skills',
    category: 'other',
    order: 14,
    showOnStack: false,
  },
  {
    name: 'Project Management',
    description: 'Management Skills',
    category: 'other',
    order: 12,
    showOnStack: false,
  },
]

export function getSkillsData(): RequiredDataFromCollectionSlug<'skills'>[] {
  return skills
}

export async function seedSkills(payload: Payload): Promise<void> {
  const skillsData = getSkillsData()

  for (const skill of skillsData) {
    await payload.create({
      collection: 'skills',
      data: skill,
      context: { disableRevalidate: true },
    })
    payload.logger.info(`Created skill: ${skill.name}`)
  }
}
